### ISSUE TITLE
incompatibility issue with github.com/quic-go/quic-go v0.45.1

### ISSUE THREAD

**Issue by limbo127** [folbricht/routedns#396]
hello, 
with latest go-quick release we have an incompatibility issue 
github.com/quic-go/quic-go v0.45.1

# github.com/folbricht/routedns
../../dohclient.go:343:9: cannot use &quicConnection{…} (value of type *quicConnection) as quic.EarlyConnection value in return statement: *quicConnection does not implement quic.EarlyConnection (wrong type for method NextConnection)
		have NextConnection() quic.Connection
		want NextConnection(context.Context) (quic.Connection, error)

**Comment by cbuijs** [comment]
Same here. Needed to downgrade (or not upgrade) to a previous version of quic-go (it still works with **v0.43.1**).

**Comment by folbricht** [comment]
I'm traveling this without access to a dev machine. But if anyone wants to try to make a PR for it I can approve it

**Comment by cbuijs** [comment]
@folbricht That sounds like "Sitting on the beach with a margarita" :-).

I might give it a shot later, but I suck at these kind of things :-)

**Comment by cbuijs** [comment]
Compile works indeed when including `issue-396` branch. The resulting executable seems to be working just fine. Will run it for a while to see if somethings pops up.
