### ISSUE TITLE
golang 1.21 error

### ISSUE THREAD

**Issue by limbo127** [folbricht/routedns#321]
hello, 
does not compile with golang 1.21 
../../dohclient.go:419:35: cannot use udpConn (variable of type *net.UDPConn) as context.Context value in argument to quic.DialEarly: *net.UDPConn does not implement context.Context (missing method Deadline)
../../dohclient.go:419:44: cannot use udpAddr (variable of type *net.UDPAddr) as net.PacketConn value in argument to quic.DialEarly: *net.UDPAddr does not implement net.PacketConn (missing method Close)
../../dohclient.go:419:53: cannot use hostname (variable of type string) as net.Addr value in argument to quic.DialEarly: string does not implement net.Addr (missing method Network)
../../doqlistener.go:79:14: cannot use quic.ListenAddr(s.addr, s.opt.TLSConfig, &quic.Config{}) (value of type *quic.Listener) as quic.Listener value in assignment

Regards, 
Nicolas

**Comment by limbo127** [comment]
quic need update and seems routedns using old quic function

**Comment by folbricht** [comment]
I updated the library and can now build it with Go 1.21. Can you try out `issue-321` to confirm it works? I haven't tested the quic server functionality, though it's probably fine since it only needed a very minor change.

**Comment by limbo127** [comment]
Hello,
it's ok for me
Thanks
Nicolas

Le dim. 20 août 2023 à 11:02, Frank Olbricht ***@***.***> a
écrit :
